username_textbox_id = "UserName"
password_textbox_id = "Password"
login_button_classname = "btn-lg"
mainpage_button_xpath = "(//div[text()='حل تمرین'])[2]"
invalid_login_xpath = "//span[text()='نام کاربری یا کلمه عبور اشتباه وارد شده است']"
blank_username_password = "//span[text()='نام کاربری یا کلمه عبور وارد نشده است']"
