login_button = "//button[contains(@class,'signin-btn py-2')]"
username_textbox = "Username"
next_step = "//a[contains(@class,'btn btn-primary')]"
password_textbox = "Password"
submit = "//a[contains(@class,'btn btn-primary')]"
mainpage_button_xpath = "//span[text()='ملیکا سجودی']"
invalid_username = "//p[text()='شماره موبایل یا آدرس ایمیل وارد شده معتبر نمی باشد.']"
invalid_password = "//p[text()='رمزعبور وارد شده صحیح نمی‌باشد.']"
blank_username = "//p[text()='شماره موبایل یا آدرس ایمیل وارد شده معتبر نمی باشد.']"
blank_password = "//p[text()='رمزعبور وارد شده صحیح نمی‌باشد.']"
